name: CI/CD Pull and Build
 
on:
  push:
    branches:
      - main  # Trigger on push to main branch
 
jobs:
  pull-code-and-build:
    runs-on: self-hosted  # Must match your self-hosted runner's label
 
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
 
      - name: Pull code from main Branch
        run: "cd /home/dev/TrangoEnterprise/ && git pull origin main"
